---
abstract: 'calculate the phase only correlation'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.63
  Test::More: 0.98
  Test::Most: 0.31
configure_requires:
  ExtUtils::MakeMaker: 6.63
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-PhaseOnlyCorrelation
no_index:
  directory:
    - t
    - inc
requires:
  List::MoreUtils: 0.33
  Math::FFT: 1.28
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/moznion/Statistics--PhaseOnlyCorrelation.git
version: 0.01
